apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellopipe-ingress
  namespace: practice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hellopipe.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hellopipe-svc
            port:
              number: 3000
