apiVersion: v1
kind: Service
metadata:
  name: hellopipe-service
  namespace: practice
spec:
  type: ClusterIP
  selector:
    app: hellopipe
  ports:
    - name: http
      port: 3000
      targetPort: 3000
